#!/bin/sh

set -e  # Exit immediately if any command fails
export PATH="$HOME/.cargo/bin:$PATH"

cd src/rcounter
./vendor-update.sh

echo "[INFO] Generating inst/AUTHORS..."
"${R_HOME}/bin/Rscript" vendor-authors.R