# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_guideCounterWrapper_wrappers", use_symbols = TRUE, package_name = "guideCounterWrapper")

#' @usage NULL
#' @useDynLib guideCounterWrapper, .registration = TRUE
NULL

#' Function to call the fqtk CLI command for demux.
#' Exposes the demux functionality as a Rust function that can be called from R.
#' @export
guidecounter_count <- function(input, library, offset_min_fraction, output) .Call(wrap__guidecounter_count, input, library, offset_min_fraction, output)


# nolint end
