# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_counter_wrappers", use_symbols = TRUE, package_name = "counter")

#' @usage NULL
#' @useDynLib counter, .registration = TRUE
NULL

#' Function to call the fqtk CLI command for demux.
#' Exposes the demux functionality as a Rust function that can be called from R.
#' @export
run_counter <- function(inputs, library, offset_min_fraction, output) .Call(wrap__run_counter, inputs, library, offset_min_fraction, output)


# nolint end
